name: test

on:
  push:
    branches:
      - main

jobs:
  run:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.3

      - name: Get Repo List
        id: repo
        uses: ./
        with:
          my_token: ${{ secrets.REPO_TOKEN }}

      - name: Echo repoList
        run: echo repoList:${{steps.repo.outputs.repoList}}

      - name: Echo repoList_ALL
        run: echo repoList_ALL:${{steps.repo.outputs.repoList_ALL}}

      - name: Echo repoList_PRIVATE
        run: echo repoList_PRIVATE:${{steps.repo.outputs.repoList_PRIVATE}}

      - name: Echo repoList_FORK
        run: echo repoList_FORK:${{steps.repo.outputs.repoList_FORK}}

      - name: Echo privateList
        run: echo privateList:${{steps.repo.outputs.privateList}}

      - name: Echo privateList_ALL
        run: echo privateList_ALL:${{steps.repo.outputs.privateList_ALL}}

      - name: Echo forkList
        run: echo forkList:${{steps.repo.outputs.forkList}}

      - name: Echo forkList_ALL
        run: echo forkList_ALL:${{steps.repo.outputs.forkList_ALL}}

      - name: Fetch error
        uses: ./
        with:
          my_token: ${{ secrets.GITHUB_TOKEN }}
