name: test

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Repo list generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.3

      - name: Get Repo List
        id: repo
        uses: ./
        with:
          my_token: ${{ secrets.REPO_TOKEN }}

      - name: Echo Output
        run: |
          echo repoList:${{steps.repo.outputs.repoList}}
          echo repoList_ALL:${{steps.repo.outputs.repoList_ALL}}
          echo repoList_PRIVATE:${{steps.repo.outputs.repoList_PRIVATE}}
          echo repoList_FORK:${{steps.repo.outputs.repoList_FORK}}
          echo privateList:${{steps.repo.outputs.privateList}}
          echo forkList:${{steps.repo.outputs.forkList}}
