name: 'Repo list generator'

on:
  push:
    branches:
      - test-github_token

jobs:
  run:
    name: Repo list generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.3

      - name: Get Repo List for user
        id: repo
        uses: ./
        with:
          my_token: ${{ secrets.REPO_TOKEN }}

      - name: Echo Output for user
        run: |
          echo repo: ${{steps.repo.outputs.repo}}
          echo repoList: ${{steps.repo.outputs.repoList}}
          echo repoList_ALL: ${{steps.repo.outputs.repoList_ALL}}
          echo repoList_PRIVATE: ${{steps.repo.outputs.repoList_PRIVATE}}
          echo repoList_FORK: ${{steps.repo.outputs.repoList_FORK}}
          echo privateList: ${{steps.repo.outputs.privateList}}
          echo forkList: ${{steps.repo.outputs.forkList}}

      - name: Get Repo List for user
        id: repo1
        uses: ./
        with:

      - name: Echo Output for user
        run: |
          echo repo: ${{steps.repo1.outputs.repo}}
          echo repoList: ${{steps.repo1.outputs.repoList}}
          echo repoList_ALL: ${{steps.repo1.outputs.repoList_ALL}}
          echo repoList_PRIVATE: ${{steps.repo1.outputs.repoList_PRIVATE}}
          echo repoList_FORK: ${{steps.repo1.outputs.repoList_FORK}}
          echo privateList: ${{steps.repo1.outputs.privateList}}
          echo forkList: ${{steps.repo1.outputs.forkList}}

      - name: Get Repo List for organization
        id: repo2
        uses: ./
        with:
          my_token: ${{ secrets.REPO_TOKEN }}
          user: yi-xu-test-organization

      - name: Echo Output for organization
        run: |
          echo repo: ${{steps.repo2.outputs.repo}}
          echo repoList: ${{steps.repo2.outputs.repoList}}
          echo repoList_ALL: ${{steps.repo2.outputs.repoList_ALL}}
          echo repoList_PRIVATE: ${{steps.repo2.outputs.repoList_PRIVATE}}
          echo repoList_FORK: ${{steps.repo2.outputs.repoList_FORK}}
          echo privateList: ${{steps.repo2.outputs.privateList}}
          echo forkList: ${{steps.repo2.outputs.forkList}}

      - name: Get Repo List for organization
        id: repo3
        uses: ./
        with:
          user: yi-xu-test-organization

      - name: Echo Output for organization
        run: |
          echo repo: ${{steps.repo3.outputs.repo}}
          echo repoList: ${{steps.repo3.outputs.repoList}}
          echo repoList_ALL: ${{steps.repo3.outputs.repoList_ALL}}
          echo repoList_PRIVATE: ${{steps.repo3.outputs.repoList_PRIVATE}}
          echo repoList_FORK: ${{steps.repo3.outputs.repoList_FORK}}
          echo privateList: ${{steps.repo3.outputs.privateList}}
          echo forkList: ${{steps.repo3.outputs.forkList}}
